"""Initial migration

Revision ID: 59824f09d717
Revises: f909f79754cf
Create Date: 2025-12-03 15:17:43.532995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59824f09d717'
down_revision = 'f909f79754cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'General'"), nullable=True))

    # ### end Alembic commands ###
