"""Add additional features columns

Revision ID: f909f79754cf
Revises: cdf71144ebce
Create Date: 2025-12-03 01:04:47.385695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f909f79754cf'
down_revision = 'cdf71144ebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pages_read', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('finish_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_image')
        batch_op.drop_column('finish_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('notes')
        batch_op.drop_column('pages_read')
        batch_op.drop_column('total_pages')

    # ### end Alembic commands ###
